<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magento\OfflinePayments\Block\Info\Purchaseorder
 */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <strong><?= $block->escapeHtml(__('Purchase Order Number')) ?></strong>
        <span class="number"><?= $block->escapeHtml($block->getInfo()->getPoNumber()) ?></span>
    </dd>
    <dd class="content">
        <strong><?= $block->escapeHtml(__('Attached file')) ?></strong>
        <span class="link"><a href="<?= $block->escapeHtml($block->getPoAttachment()) ?>" download><?= __("Link to the file") ?></a></span>
    </dd>
</dl>
